### ISSUE TITLE
can't get it running in my BMW

### ISSUE THREAD

**Issue by tntrio** [KLUSEK/BMW-RPi-iBUS#1]
Hello, 
first thank you for your work!
I have an issue that I think is not on your sw side but maybe you can help me with that.
I followed your readme, connect my iphone via bluetooth, and start the agent script via terminal manually.
The connection to BMW is good, when I start spotify for exampe I get the title information showed on radio  display and also in terminal. The only problem is that the sound is still coming out of my phone and I can't coose a bluetooth device to play my music but in settings on phone it shows connected to the pi.

hope you can help me, tried several thinks but without effort.
Thank you and sorry for my bad english :(

Mario

**Comment by KLUSEK** [comment]
Hi,

Unfortunately I don't have any iPhone to check the problem.
Could you try any other device like Android or PC instead and tell if the same problem appears?

In fact that Pulseaudio is really responsible for overriding the BT Profile. I would say there is a real problem, but weird thing is that you say you are able to see song titles in the terminal - if audio profile is not working it should be possible i think.

**Comment by emptyq** [comment]
Hello,
Can this be done via the Raspberry PI 3 B v1.2?
what addons will I need to do it?
Thank you in advance.

Best Regards,
Stefan

**Comment by tntrio** [comment]
Hi, hopefully I will have time to test it with an andriod device this week.
I will report you my progress here!

**Comment by tntrio** [comment]
Hi,
hopefully I will have time this week to test it with an android device. What I´ve forgot to tell is that I am using an Pi Zero W with integrated bluetooth. If it´s not working I will install it all on an "normal" Pi Zero with USB-bluetooth-dongle and test it again.
I will report you my progress here, thanks for your work!

**Comment by KLUSEK** [comment]
Ah, it might be the reason.

I use one of the cheap Chinese BT adapters, never tried built-in one.
Let me know! :)

**Comment by nemanjacosovic** [comment]
@tntrio I've ran into this issue before. You need to change the BT adapter settings to discoverable.
https://stackoverflow.com/questions/37927606/how-do-i-make-raspberry-pi-3-discoverable-for-ios-and-corebluetooth

@KLUSEK could you please do an English audio version of your video, about 10-15 minutes. It would be really helpful to have the entire process or at least parts of the process shown.

Thank you!

**Comment by KLUSEK** [comment]
@nemanjacosovic which video you mean exactly? I've got only one and it's 3 minutes long only.
When I was recording the video there was no plan to share this on GitHub - sorry for that.

**Comment by nemanjacosovic** [comment]
@KLUSEK The one where you've showcased BMW I-BUS + Raspberry Pi and Bluetooth. 

"Raspberry Pi + IBUS + Bluetooth to control media in BMW E46"
https://www.youtube.com/watch?v=W3VJtcYz3fo

I would be very grateful if you could do a 10-15 minute video about it. Showing few points and describing the process.

**Comment by KLUSEK** [comment]
Sorry but it might be difficult now to show everything while it's blended into car wirring.

Maybe some day if I will be doing some further modifications :)

**Comment by nemanjacosovic** [comment]
@KLUSEK Sorry to bug you, but can you at least do a video in English?
Explain, on a sketch or on whiteboard how you've connected everything? You don't need to take out anything, just draw a simple diagram.
I would like to have the exact same build in my car.

**Comment by KLUSEK** [comment]
Maybe one day I will re-record the video in english, because I added some feature ... But it never was my intention to make a online manual .. I was doing it for myself and I don't have much "materials" from bulding proccess time.

Nevertheless I made this for you to help ;)

![connections_schema](https://user-images.githubusercontent.com/1569797/38021885-51879fec-327e-11e8-8344-5b1dcc8946b5.jpg)

Ofcourse you can use Rpi Zero W which has BT/WiFi onboard already, then you only need simply 2-port USB Hub. You can also use other raspberry with analog audio output, but it has poor audio quality, that's why I used external DAC

In video description you can find parts list.
