### ISSUE TITLE
Needle sweep przez k-bus

### ISSUE THREAD

**Issue by EmanuelMos** [KLUSEK/BMW-RPi-iBUS#13]
Witam, 
Od dłuższego czasu próbuję zrobić "Needle sweep" w e46. Nie znam się za bardzo na kodowaniu więc spróbowałem przy pomocy Arduino bezpośrednio wpinając się w silniczki krokowe. Na sucho (czyli bez podłączania zegarów do samochodu) działało. Niestety po podłączeniu nie ruszają się. Domyślam się, że po włączeniu zapłonu silniczki dostają już impulsy od sterownika w samochodzie które zagłuszają moje z Arduino. Przez przypadek wpadłem na Pana projekt i po zobaczeniu jakie są możliwości np. aktualizacja godziny wpadło mi do głowy pytanie. Jest możliwość zrobić ten cieszący oko dodatek przez k-bus? Bardzo proszę o jakąś odpowiedź.

Pozdrawiam Serdecznie,

**Comment by KLUSEK** [comment]
Witam,

Juz od dawna nie mam E46, ale na 99% da się sterować wskazówkami przez iBUS.
Poszukaj w necie jak ludzie przerabiają zegary z BMW, aby uzywać ich w swoich grach PC/Symulatorach.

Tam za pomocą sygnałów ustawiają konkretną wartość predkosci i obrotów, wiec bez problemu można zrobić Needle sweep.

Pozdrawiam
