### ISSUE TITLE
Flash

### ISSUE THREAD

**Issue by nikitrk** [KLUSEK/BMW-RPi-iBUS#5]
Hello, I am very impressed of your project. These days i am  going to do it, but before I start one question occur.  How to make it, to stream music stored on an SD card or Flash drive. Of course without removing the bluetooth function. Thank you.

**Comment by KLUSEK** [comment]
Hi,

I didn't add functionality of playing audio from local storage because I didn't need that.
You need to figure it out by yourself and add this to the code.

**Comment by nikitrk** [comment]
May I ask one more thing. How do you connect the external dac to your Cd. Which pinout did you use, left or the right group of pins. Sorry if my question looks stupid. Thank you, have a nice day.

**Comment by KLUSEK** [comment]
You need to have AUX input in you car stereo unit. Google for BMW E46 AUX :)
