### ISSUE TITLE
How can i run your files?

### ISSUE THREAD

**Issue by Encik7** [KLUSEK/BMW-RPi-iBUS#6]
Hello,

i have your files on my home/pi/bmw/
i have make a file in systemd/system/ called bmw-agent.service and copy yours to the file.

is that enough?

**Comment by KLUSEK** [comment]
Hi, 

You can always run it manually: python path/to/bmw-agent.py

**Comment by Encik7** [comment]
Yes i now, bud i dont wont start it manually.

Chcę zrobić tak jak masz ty że jak przekręcisz kluczyk to startuje.

**Comment by KLUSEK** [comment]
Nadaj skryptowi bmw-agent.service uprawnienia do wykonywania (chmod +x)
nastepnie dodaj ten skrypt do systemd:

sudo systemctl enable bmw-agent
sudo systemctl start bmw-agent

**Comment by Encik7** [comment]
Wielkie dzięki
