### ISSUE TITLE
ibus doesnt interface to CD player

### ISSUE THREAD

**Issue by zarboz** [KLUSEK/BMW-RPi-iBUS#7]
I have business CD Player

I see you enumerate the radio but i dont see where it sends any kind of enable to be an audio source IE aux/cd/mp3 etc

**Comment by KLUSEK** [comment]
It uses standard AUX functionality

**Comment by zarboz** [comment]
@KLUSEK So intended flow is for raspi -> BMW AUX and while head unit on AUX it displays Bluetooth song data?

**Comment by KLUSEK** [comment]
Correct

**Comment by zarboz** [comment]
Thank you I might be able to alter for my CD player headunit to use in place of Cd Changer I can alter the code you have 
request_for_radio_status
request_for_radio_mode_switch

these look like ones i can manipulate to send ibus commands to get CD to play (with extra wires in trunk since i dont have aux)
