### ISSUE TITLE
CD Switches Instead of Aux? 

### ISSUE THREAD

**Issue by Encik7** [KLUSEK/BMW-RPi-iBUS#8]
Is threre a possible run that with the CD Switch connection? I have a CD Radio of 01.2001 and the aux Mode is first by 09.2002 Radios...

**Comment by zarboz** [comment]
@Encik7  I am trying to implement a cd changer switch signal as everything else seems to be working so far on my 200 e39 with business radio

**Comment by zarboz** [comment]
@Encik7  I tried pretty hard and couldnt figure it out

I found a 2005 x5 at my local junk yard and got the cd player out of it for 30$ previous owner had aux cable installed so it made everything a breeze


you can look at my fork of this branch to see what I tried to do for CD announcing but it didnt work
