### ISSUE TITLE
Not sure if this should be opened as an issue

### ISSUE THREAD

**Issue by zarboz** [KLUSEK/BMW-RPi-iBUS#9]
I don't write python as my main language and i took a stab at introducing a cd changer listen/reply but I dont think it is triggering properl

```

def radio_cd_respond(self):
    	self.ibus.send("1804FF0200E0")

 def send_cd_playing(self):
        """
        @return 68 FF 18 38 00 00
        """
        self.ibus.send("68FF1801")   
             
    def announce_cd(self):
		self.ibus.send("1804FF0201E1")
```

I added these into ibus.py just fine
and call to them in agent.py

What I am basing this previous information on is a project called PyBus which also uses python to talk to the ibus and emulate a cd changer

its main function calls to 2 ibus commands 
one gets sent every 3 seconds it appears and the other gets sent once when the car is turned on / RT button pushed / when RAD asks for it 

Structure I am referencing from another working project is like:
```
if packet heard == '6818FF01"
  WRITE.Packet'18', 'FF', '02','00'
```

this above references the "poll response" def

```
def d_cdPollResponse(packet):
  pB_ticker.disableFunc("announce") # stop announcing
  pB_ticker.disableFunc("pollResponse")
  pB_ticker.enableFunc("pollResponse", 30)
```

can you lend me any insight towards this ? I have forked your repo and attempted to add some lines to agent.py in order to triger these events as it looks like i can use your existing framework to listen for raw iBus and send a command from ibus.py

**Comment by zarboz** [comment]
Announcing cd
Unexpected packet length. Dump: 1804ff0201c006683100120b866812c0234020464d20033130372e3504205354dfc006683100124bc6c006683100120b866810c02340204e4f205441504520202020dac006683100124bc6c006683100120b866812c0234020464d20033130372e3504205354dfc006683100124bc6c0036801aa6804ff0200911804ff0200


im not sure why i cant parse this but i see my 2 messages in this 
1804ff0201
1804ff0200

these are to be sent to the ibus to announce the cd player and reply to a Poll sent by MID

**Comment by zarboz** [comment]
@KLUSEK  can you potentially help me out with the syntax of how ibus packets need to be structured and sent via your ibus.py im trying to mimick what I see in other def's but its not outputting properly i think either due to lenght or xor checksum and im not sure how to tackle it

**Comment by KLUSEK** [comment]
Hi,

It's been some time while I last time doing anything in this project. I don't remember everything now.
What could help you is file **ibus_test.py** which is perfect to do some checkings.

There are two methods:

- onIBUSready()
It can be used to send your raw ibus packet, example:

`def onIBUSready():
    ibus.send("packet_raw_string")`

or if you need to calculate XOR checksum do it like this:

`def onIBUSready():
    packet = IBUSPacket(source_id, length, destination_id, data)
    ibus.send("packet.raw")`

here you can read more about how packet is built: https://github.com/KLUSEK/BMW-RPi-iBUS/blob/master/docs/IBUSInsideDRAFTREV5.pdf (page no 9)

- all received ibus packets can be printout in **onIBUSpacket(packet)**

---

I don;t know for now what is the problem with parsing such long string - to be honest I've never seen such long packet. Probably my parser doing something wrong and doesn't split it properly

**Comment by zarboz** [comment]
Do I need to calculate length by octet or by digit? 

Or does your software calculate length for me

**Comment by KLUSEK** [comment]
It doesn calculate it for you.

Just pass all parameters to method **packet = IBUSPacket(source_id, length, destination_id, data)** 

then you can get whole packet (including xor at the end) by reading **packet.raw**

**Comment by zarboz** [comment]
@KLUSEK  according to that document the length is calculated with the xor checksum 


How can i determine length if software determines checksum?

Can i use a calculator or something to determine the checksum in order to specify length of packet?

**Comment by KLUSEK** [comment]
xor is always 1 byte length. So just include this to your length value

**Comment by zarboz** [comment]
@KLUSEK  can i make the command run at X interval?

IE 
 packet = IBUSPacket(source_id, length, destination_id, data) ibus.send("packet.raw",3)
meaning i wanna send every 3 seconds

**Comment by zarboz** [comment]
```
def onIBUSready():
    packet = IBUSPacket (source_id="18",
    					 length="04",
    					 destination_id="ff",
    					 data="0201")
    ibus.send("packet.raw")
```

**Comment by KLUSEK** [comment]
You can just write a loop

**Comment by zarboz** [comment]
@KLUSEK  would it be best to use threading for this loop? 

I am teaching myself python for this 

in C or C+ i would just use some if else statements or maybe a case switch

python seems to run more like an open ended program rather than a loop


i tried using a loop function written out like:

```
def sendannounce():
   threading.Timer(3,sendannounce).start()
   def onIBUSready():
    packet = IBUSPacket (source_id="18",
    					 length="04",
    					 destination_id="ff",
    					 data="0201")
    ibus.send("packet.raw")
sendannounce()
```


but when i add this code then i get "cannt connect to /usb/ttyusb0" error when starting python

I greatly appreciate the replies

**Comment by zarboz** [comment]
@KLUSEK  

OK So... I have agent.py modified to hear the Poll request from MID to see if CDC is connected and send back a reply 

I have been trying to add loops to the reply but it breaks the whole structure of your code

is there an existing loop framework I can use?

**Comment by zarboz** [comment]
I went to the junk yard and bought a CD53 cd player so i can run an AUX input 


thanks for the software makes things great
